# Mario: Basic Tasks 

#### Goal: Mario pick-up ladder, go to princess(goal) and avoid Bowser(obstacle) in 6x6 grid

1. Environment definition
2. State and Reward function
3. Q-learning update rule and policy (epsilon greedy and softmax)
4. Run and measure performance for one episode, 10, 50, 100


* observation_space = state space as the grid is a fully observable environment 

In [404]:
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch import nn
import gym
from gym import Env, logger, spaces, utils
import random
from enum import Enum

In [405]:
# The Warehouse is divided into a grid. Use these 'tiles' to represent the objects on the grid.
class GridTile(Enum):
    _Floor = 0
    Mario = 1
    Ladder = 2
    Weapon = 3
    Dragon = 4
    Princess = 5

    # Return the first letter of tile nme 
    def __str__(self):
        return self.name[:1]

In [406]:
class gridEnv(gym.Env):
    def __init__(self, gridsize=(6, 6), princess_position=(4, 4), dragon_position=(3,2),weapon_position=(4,5), ladder_position=(1,1)):
        super(gridEnv, self).__init__()
        
        # Grid size 6x6
        self.gridsize = gridsize
        
        # Position of goal: Princess Peach at (4,4)
        self.princess_position = princess_position

        # Position of obstacle: dragon at (3,2)
        self.dragon_position = dragon_position
        
        # Position of weapon at (4,5)
        self.weapon_position = weapon_position

        # Position of tool: Ladder at (1,1)
        self.ladder_position = ladder_position  
        
        # Define action space: up, down, left, right
        self.action_space = spaces.Discrete(4)
        
        # Define observation space (state space): 0...5 rows/columns 
        # Each position of the agent in the grid is a state 
        self.observation_space = spaces.Box(low=0, high=max(self.gridsize), shape=(2,))
        
        # Define state where agent starts, here it's (1,0)
        self.state = np.array([1, 0]) 

        # Initialise 6x6 grid where positions will be stored
        self.grid = np.zeros(self.gridsize)  
        
        # Define ladder check
        self.ladder_pickup = False
        
        # Define weapon check
        self.weapon_pickup = False
        
        # Define if terminal state reached = learning episode ended
        self.done = False 


    def reset(self):
        # Reset the Mario's position and the grid
        self.state = np.array([1, 0])  
        self.done = False
        
        # Reset the grid (zeros) and place the goal position
        self.grid = np.zeros(self.gridsize)
        # Store positions, e.g. grid[4,4] = 2 is the princess position 
        self.grid[self.princess_position[0], self.princess_position[1]] = 2  
        self.grid[self.dragon_position[0], self.dragon_position[1]] = 3
        self.grid[self.ladder_position[0], self.ladder_position[1]] = 4
        self.grid[self.weapon_position[0], self.weapon_position[1]] = 5
        
        return self.state

    
    def step(self, action):
        # Move the agent based on the action: up, down, left, right
        if action == 0:  # Move up
            self.state[0] = max(0, self.state[0] - 1)
        elif action == 1:  # Move down
            self.state[0] = min(self.gridsize[0] - 1, self.state[0] + 1)
        elif action == 2:  # Move left
            self.state[1] = max(0, self.state[1] - 1)
        elif action == 3:  # Move right
            self.state[1] = min(self.gridsize[1] - 1, self.state[1] + 1)
                
        # Compute reward and check if episode ends
        reward = self.compute_reward()
        
        return self.state, reward, self.done

    
    def compute_reward(self):
        # Check if the agent reached the goal
        if np.array_equal(self.state, self.princess_position):
            if self.ladder_pickup == True:
                reward = 150
                self.done = True
            else:
                reward = -150
                
        elif np.array_equal(self.state, self.weapon_position):
            if self.weapon_pickup == False:
                reward = 20
                self.weapon_pickup == True

        elif np.array_equal(self.state, self.dragon_position):
            if self.weapon_pickup == True:
                reward = -10
            else:
                reward = -50
                self.done = True #Hitting dragon is a terminal state
            
        elif np.array_equal(self.state, self.ladder_position):
            if self.ladder_pickup == False:
                reward = 50 #small reward for picking up ladder
                self.ladder_pickup == True
        else: 
            reward = -1  #penalise if step taken with no win

        return reward


    def render(self, mode='human'):
        # Clear the grid and update it with the agent's current position
        self.grid = np.zeros(self.gridsize)
        # Mario
        self.grid[self.state[0], self.state[1]] = 1
        # Princess Peach
        self.grid[self.princess_position[0], self.princess_position[1]] = 2
        
        # Dragon 1,2
        self.grid[self.dragon_position[0], self.dragon_position[1]] = 3
        self.grid[self.ladder_position[0], self.ladder_position[1]] = 4
        
        # Plot the grid
        plt.imshow(self.grid, cmap='Blues', interpolation='nearest')
        #plt.xticks([])  
        #plt.yticks([])  
        plt.show()

    
    def render_2(self, mode='human'):
        # Print current state on console
        for r in range(self.gridsize[0]):
            for c in range(self.gridsize[1]):
                if ([r, c] == [self.state[0], self.state[1]]):
                    print(GridTile.Mario, end=' ')
                elif ([r,c] == [self.ladder_position[0],self.ladder_position[1]]):
                    print(GridTile.Ladder, end=' ')
                elif ([r,c] == [self.weapon_position[0],self.weapon_position[1]]):
                    print(GridTile.Weapon, end=' ')
                elif ([r,c] == [self.dragon_position[0], self.dragon_position[1]]):
                    print(GridTile.Dragon, end=' ')
                elif ([r,c] == [self.princess_position[0], self.princess_position[1]]):
                    print(GridTile.Princess, end=' ')
                else:
                    print(GridTile._Floor, end=' ')

            print() # new line
        print() # new line


In [407]:
def greedy_policy(q_table, state):
  action = np.argmax(q_table[state])
  #print(np.shape(action))
  return action


def epsilon_greedy_policy(q_table, state, epsilon, grid_width):
    flat_state = int(state[0]) * grid_width + int(state[1])  # Ensure integer index
    random_int = random.uniform(0, 1)
    if random_int > epsilon:
        action = np.argmax(q_table[flat_state])
    else:
        action = env.action_space.sample()
    return action


In [408]:
def state_to_index(state, width):
    return state[0] * width + state[1]

# Q-learning function 
def q_learning(env, alpha, gamma, epsilon, max_epsilon, epsilon_decay, min_epsilon, episodes):
    
    # Initialize Q-table with shape (36, 4) = (state, action)
    q_table = np.zeros((env.gridsize[0] * env.gridsize[1], env.action_space.n))
    #print(np.shape(q_table))
    
    for _ in range(episodes):
        state = env.reset()
        # Convert state to index
        state_index = state_to_index(state, env.gridsize[1])
        #print(state)
        done = False
        
        while not done:
            
            # Choose action based on epsilon-greedy strategy
            #max = q_table[state]
            #print(state)
            #print(q_table[state])
            
            action = epsilon_greedy_policy(q_table, state, epsilon, env.gridsize[1])
            
            #print(np.max(action))
            #print(np.shape(action))
            
            # Take the action and observe the result
            next_state, reward, done = env.step(action)
            next_state = (next_state)
            # Convert next state to index
            next_state_index = state_to_index(next_state, env.gridsize[1])  
            #print(q_table[next_state])
            
            # Update Q-table based on the Q-learning formula
            q_table[state_index, action] += alpha * (reward + gamma * np.max(q_table[next_state_index]) - q_table[state_index, action])
            #print(q_table)
            #print(np.shape(q_table)[1])
            # Move to the next state
            state = next_state
            # Update the state index
            state_index = next_state_index  
        
        # Decay epsilon to reduce exploration over time
        #epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-epsilon_decay*episodes)
        epsilon = max(min_epsilon, epsilon * epsilon_decay)
  
    return q_table

In [409]:
min_epsilon = 0.05
max_epsilon = 1.0
epsilon_decay=0.0995
epsilon = 0.1
alpha=0.1
gamma=0.99 
episodes=1

if __name__ == "__main__":
    env = gridEnv()
    state = env.reset()
    env.render_2()
    q_table = q_learning(env,alpha, gamma, epsilon, max_epsilon, epsilon_decay, min_epsilon, episodes)
    print()
    print("Trained Q-Table:")
    print(q_table)


_ _ _ _ _ _ 
M L _ _ _ _ 
_ _ _ _ _ _ 
_ _ D _ _ _ 
_ _ _ _ P W 
_ _ _ _ _ _ 


Trained Q-Table:
[[-1.00000000e-01 -1.00000000e-01 -1.00000000e-01  3.46179080e+00]
 [-1.00000000e-01  6.02524313e+01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01 -1.00000000e-01  1.57132957e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.90000000e-01 -6.53271998e-02  2.84212747e+01  2.90718907e+02]
 [ 3.05000000e-01  4.12700733e+00  2.64079197e+02 -1.90000000e-01]
 [-1.90000000e-01 -1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01 -1.00000000e-01 -1.00000000e-01  7.79727608e+00]
 [ 8.13715628e+01  0.00000000e+0

In [410]:
print(q_table)

[[-1.00000000e-01 -1.00000000e-01 -1.00000000e-01  3.46179080e+00]
 [-1.00000000e-01  6.02524313e+01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01 -1.00000000e-01  1.57132957e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.90000000e-01 -6.53271998e-02  2.84212747e+01  2.90718907e+02]
 [ 3.05000000e-01  4.12700733e+00  2.64079197e+02 -1.90000000e-01]
 [-1.90000000e-01 -1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01 -1.00000000e-01 -1.00000000e-01  7.79727608e+00]
 [ 8.13715628e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -5.00000000e+00  0.00000000e+00  0.00000000e